Add all actions to TM VMware

diff --git a/src/tm_mad/vmware/ln b/src/tm_mad/vmware/ln
--- a/src/tm_mad/vmware/ln
+++ b/src/tm_mad/vmware/ln
@@ -1,1 +1,79 @@
-../shared/ln
+#!/bin/bash
+
+# -------------------------------------------------------------------------- #
+# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
+#                                                                            #
+# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
+# not use this file except in compliance with the License. You may obtain    #
+# a copy of the License at                                                   #
+#                                                                            #
+# http://www.apache.org/licenses/LICENSE-2.0                                 #
+#                                                                            #
+# Unless required by applicable law or agreed to in writing, software        #
+# distributed under the License is distributed on an "AS IS" BASIS,          #
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
+# See the License for the specific language governing permissions and        #
+# limitations under the License.                                             #
+#--------------------------------------------------------------------------- #
+
+# ln fe:SOURCE host:remote_system_ds/disk.i vmid dsid
+#   - fe is the front-end hostname
+#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
+#   - host is the target host to deploy the VM
+#   - remote_system_ds is the path for the system datastore in the host
+#   - vmid is the id of the VM
+#   - dsid is the target datastore (0 is the system datastore)
+
+SRC=$1
+DST=$2
+
+VMID=$3
+DSID=$4
+
+if [ -z "${ONE_LOCATION}" ]; then
+    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
+else
+    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
+fi
+
+. $TMCOMMON
+
+#-------------------------------------------------------------------------------
+# Set dst path and dir
+#-------------------------------------------------------------------------------
+SRC_PATH=`arg_path $SRC`
+SRC_PATH="../../${SRC_PATH##"$DS_DIR/"}"
+
+DST_PATH=`arg_path $DST`
+DST_HOST=`arg_host $DST`
+DST_DIR=`dirname $DST_PATH`
+
+#-------------------------------------------------------------------------------
+# Link (ln) SRC into DST
+#-------------------------------------------------------------------------------
+
+if [ "$SSH" == "yes" ]; then
+	ssh_make_path $DST_HOST $DST_PATH
+
+	# It's a folder, make links for all elements
+    SRC_FOLDER_NAME=`basename $SRC_PATH`
+    SRC_WITH_NO_FOLDER=`dirname $SRC_PATH`
+    SRC_DS_NAME=`basename $SRC_WITH_NO_FOLDER`
+	REL_SRC_PATH="../../../$SRC_DS_NAME/$SRC_FOLDER_NAME"
+
+	log "Link all files in $SRC_PATH to $DST_PATH"
+
+LINK_SCRIPT=$(cat <<EOF
+for file in \$(cd $DST_DIR  ; find $SRC_PATH -type f); do
+	FNAME=\$(basename \$file)
+	(cd $DST_PATH ;  ln -sf $REL_SRC_PATH/\$FNAME $DST_PATH/$FNAME)
+done
+EOF
+)
+	ssh_exec_and_log $DST_HOST "$LINK_SCRIPT" "Could not link dir files from source DS to system DS"
+else
+	log "Cannot link files without SSH enabled on the ESX hosts"
+	exit 1
+fi
+
+exit 0
