Feature #2027: Fix paths and requires

diff --git a/src/flow/bin/oneflow-server b/src/flow/bin/oneflow-server
--- a/src/flow/bin/oneflow-server
+++ b/src/flow/bin/oneflow-server
@@ -17,19 +17,19 @@
 #--------------------------------------------------------------------------- #
 
 if [ -z "$ONE_LOCATION" ]; then
-    FLOW_PID=/var/run/one/appflow-server.pid
-    FLOW_SERVER=/usr/lib/one/ruby/oneapps/flow/controllers/appflow-server.rb
-    FLOW_LOCK_FILE=/var/lock/one/.appflow.lock
-    FLOW_LOG=/var/log/one/appflow-server.log
-    FLOW_LOG_ERROR=/var/log/one/appflow-server.error
-    FLOW_ETC=/etc/one/appflow-server.conf
+    FLOW_PID=/var/run/one/oneflow.pid
+    FLOW_SERVER=/usr/lib/one/oneflow/oneflow-server.rb
+    FLOW_LOCK_FILE=/var/lock/one/.oneflow.lock
+    FLOW_LOG=/var/log/one/oneflow.log
+    FLOW_LOG_ERROR=/var/log/one/oneflow.error
+    FLOW_CONF=/etc/one/oneflow-server.conf
 else
-    FLOW_PID=$ONE_LOCATION/var/appflow-server.pid
-    FLOW_SERVER=$ONE_LOCATION/lib/ruby/oneapps/flow/controllers/appflow-server.rb
-    FLOW_LOCK_FILE=$ONE_LOCATION/var/.appflow.lock
-    FLOW_LOG=$ONE_LOCATION/var/appflow-server.log
-    FLOW_LOG_ERROR=$ONE_LOCATION/var/appflow-server.error
-    FLOW_ETC=$ONE_LOCATION/etc/appflow-server.conf
+    FLOW_PID=$ONE_LOCATION/var/oneflow.pid
+    FLOW_SERVER=$ONE_LOCATION/lib/oneflow/oneflow-server.rb
+    FLOW_LOCK_FILE=$ONE_LOCATION/var/.oneflow.lock
+    FLOW_LOG=$ONE_LOCATION/var/oneflow.log
+    FLOW_LOG_ERROR=$ONE_LOCATION/var/oneflow.error
+    FLOW_CONF=$ONE_LOCATION/etc/oneflow-server.conf
 fi
 
 setup()
@@ -39,8 +39,8 @@ setup()
       FLOWPID=`cat $FLOW_PID`
       ps $FLOWPID > /dev/null 2>&1
       if [ $? -eq 0 ]; then
-        echo "AppFlow Server is still running (PID:$FLOWPID)."
-        echo "Please try 'appflow-server stop' first."
+        echo "OneFlow Server is still running (PID:$FLOWPID)."
+        echo "Please try 'oneflow-server stop' first."
         exit 1
       fi
     fi
@@ -58,14 +58,14 @@ start()
 
   touch $FLOW_LOCK_FILE
 
-  # Start the appflow-server daemon
+  # Start the oneflow-server daemon
   ruby $FLOW_SERVER >$FLOW_LOG 2>$FLOW_LOG_ERROR &
 
   LASTRC=$?
   LASTPID=$!
 
   if [ $LASTRC -ne 0 ]; then
-        echo "Error executing appflow-server."
+        echo "Error executing oneflow-server."
         echo "Check $FLOW_LOG_ERROR and $FLOW_LOG for more information"
     exit 1
   else
@@ -76,12 +76,12 @@ start()
   ps $LASTPID > /dev/null 2>&1
 
   if [ $? -ne 0 ]; then
-        echo "Error executing appflow-server."
+        echo "Error executing oneflow-server."
         echo "Check $FLOW_LOG_ERROR and $FLOW_LOG for more information"
     exit 1
   fi
 
-  echo "appflow-server started"
+  echo "oneflow-server started"
 }
 
 #
@@ -90,11 +90,11 @@ start()
 stop()
 {
   if [ ! -f $FLOW_PID ]; then
-    echo "Couldn't find appflow-server process pid."
+    echo "Couldn't find oneflow-server process pid."
     exit 1
   fi
 
-  # Kill the appflow-server daemon
+  # Kill the oneflow-server daemon
 
   kill -INT `cat $FLOW_PID` > /dev/null 2>&1
 
@@ -102,7 +102,7 @@ stop()
   rm -f $FLOW_PID > /dev/null 2>&1
   rm -f $FLOW_LOCK_FILE &> /dev/null
 
-  echo "appflow-server stopped"
+  echo "oneflow-server stopped"
 }
 
 
@@ -115,7 +115,7 @@ case "$1" in
   stop
   ;;
   *)
-  echo "Usage: appflow-server {start|stop}" >&2
+  echo "Usage: oneflow-server {start|stop}" >&2
   exit 3
   ;;
 esac
