F OpenNebula/one#6911: LVM thin
Signed-off-by: Guillermo Ramos <gramos@opennebula.io>
Co-authored-by: Ruben S. Montero <rsmontero@opennebula.org>

diff --git a/src/tm_mad/fs_lvm_ssh/delete b/src/tm_mad/fs_lvm_ssh/delete
--- a/src/tm_mad/fs_lvm_ssh/delete
+++ b/src/tm_mad/fs_lvm_ssh/delete
@@ -1,1 +1,128 @@
-../fs_lvm/delete
+#!/bin/bash
+
+# -------------------------------------------------------------------------- #
+# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
+#                                                                            #
+# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
+# not use this file except in compliance with the License. You may obtain    #
+# a copy of the License at                                                   #
+#                                                                            #
+# http://www.apache.org/licenses/LICENSE-2.0                                 #
+#                                                                            #
+# Unless required by applicable law or agreed to in writing, software        #
+# distributed under the License is distributed on an "AS IS" BASIS,          #
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
+# See the License for the specific language governing permissions and        #
+# limitations under the License.                                             #
+#--------------------------------------------------------------------------- #
+
+# DELETE <host:remote_system_ds/disk.i|host:remote_system_ds/>
+#   - host is the target host to deploy the VM
+#   - remote_system_ds is the path for the system datastore in the host
+
+DST=$1
+VM_ID=$2
+DS_ID=$3
+
+if [ -z "${ONE_LOCATION}" ]; then
+    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
+else
+    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
+fi
+
+DRIVER_PATH=$(dirname $0)
+XPATH="${DRIVER_PATH}/../../datastore/xpath.rb"
+
+source $TMCOMMON
+source ${DRIVER_PATH}/../../etc/tm/fs_lvm/fs_lvm.conf
+source ${DRIVER_PATH}/../../datastore/libfs.sh
+
+#-------------------------------------------------------------------------------
+# Return if deleting a disk, we will delete them when removing the
+# remote_system_ds directory for the VM (remotely)
+#-------------------------------------------------------------------------------
+DST_PATH=$(arg_path "$DST")
+DST_HOST=$(arg_host "$DST")
+DST_HOST_LVM="$DST_HOST"
+DISK_ID=$(basename ${DST_PATH} | cut -d. -f2)
+
+if [ "$(is_disk "$DST_PATH")" -eq 1 ]; then
+    DS_SYS_ID=$(echo "$DST_PATH" | $AWK -F '/' '{print $(NF-2)}')
+else
+    DS_SYS_ID=$(echo "$DST_PATH" | $AWK -F '/' '{print $(NF-1)}')
+fi
+
+if is_undeployed "$VM_ID" "$DST_HOST"; then
+
+    # get BRIDGE_LIST from datastore
+    XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
+    IFS= read -r -d '' BRIDGE_LIST < <(onedatastore show -x "$DS_SYS_ID" \
+        | $XPATH /DATASTORE/TEMPLATE/BRIDGE_LIST )
+
+    if [ -n "$BRIDGE_LIST" ]; then # If BRIDGE_LIST is not defined FE must have access to LVM cluster
+        DST_HOST_LVM=$(get_destination_host)
+    fi
+fi
+
+unset i j XPATH_ELEMENTS
+
+while IFS= read -r -d '' element; do
+    XPATH_ELEMENTS[i++]="$element"
+done < <(onevm show -x $VM_ID| $XPATH \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/LVM_THIN_ENABLE )
+
+# This will be undefined when deleting VM dirs
+LVM_THIN_ENABLE="${XPATH_ELEMENTS[j++],,}"
+
+# Get DEV
+POOL_NAME="lv-one-$VM_ID-pool"
+VG_NAME="vg-one-$DS_SYS_ID"
+DEV=$($SSH "$DST_HOST" "readlink $DST_PATH 2> /dev/null | grep \"^/dev/\"")
+
+LOCK="tm-fs_lvm-${DS_SYS_ID}.lock"
+
+# The `delete` operation is called for each disk, and then once for the VM directory
+if [ -n "$DEV" ]; then
+    # This branch takes care of the per-disk calls (deleting thin LVs)
+    if [ "${ZERO_LVM_ON_DELETE}" = "yes" ] && [ "$LVM_THIN_ENABLE" != 'yes' ]; then
+        # Activate device
+        ACTIVATE_CMD=$(cat <<EOF
+            set -ex -o pipefail
+            ${SYNC}
+            ${SUDO} ${LVSCAN}
+            ${SUDO} ${LVCHANGE} -ay "${DEV}"
+EOF
+)
+
+        exclusive "${LOCK}" 120 ssh_exec_and_log "$DST_HOST_LVM" "$ACTIVATE_CMD" \
+            "Error activating disk $SRC_PATH"
+
+        # It's separeted from ACTIVATE_CMD to avoid blocking while writing in the device
+        ssh_exec_and_log_no_error "$DST_HOST_LVM" "${DD} if=/dev/zero of=\"${DEV}\" bs=${DD_BLOCK_SIZE:-64k}" \
+            "Error cleaning $DST_PATH"
+    fi
+
+    RMCMD=$(cat <<EOF
+        ${SYNC}
+        ${SUDO} ${LVSCAN}
+        $SUDO $LVREMOVE -y '$DEV'
+        ${SYNC}
+EOF
+)
+    ERR="Error deleting LV '$DEV'"
+else
+    # And this one takes care of the VM itself. In LVM thin, delete the thin pool.
+    RMCMD=$(cat <<EOF
+        set -ex -o pipefail
+        if [ -n "\$($SUDO $LVS --noheading -S "vg_name = $VG_NAME && lv_name = $POOL_NAME")" ]; then
+            $SUDO $LVREMOVE -y '$VG_NAME/$POOL_NAME'
+        fi
+EOF
+)
+    ERR="Error deleting LV POOL '$VG_NAME/$POOL_NAME'"
+fi
+
+exclusive "${LOCK}" 120 ssh_exec_and_log "$DST_HOST_LVM" "$RMCMD" "$ERR"
+
+ssh_exec_and_log "$DST_HOST" "rm -rf \"$DST_PATH\"" \
+    "Error removing \"$DST_PATH\" from $DST_HOST"
diff --git a/src/tm_mad/fs_lvm_ssh/snap_create_live b/src/tm_mad/fs_lvm_ssh/snap_create_live
--- a/src/tm_mad/fs_lvm_ssh/snap_create_live
+++ b/src/tm_mad/fs_lvm_ssh/snap_create_live
@@ -1,1 +1,100 @@
-../common/not_supported.sh
+#!/bin/bash
+
+# -------------------------------------------------------------------------- #
+# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
+#                                                                            #
+# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
+# not use this file except in compliance with the License. You may obtain    #
+# a copy of the License at                                                   #
+#                                                                            #
+# http://www.apache.org/licenses/LICENSE-2.0                                 #
+#                                                                            #
+# Unless required by applicable law or agreed to in writing, software        #
+# distributed under the License is distributed on an "AS IS" BASIS,          #
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
+# See the License for the specific language governing permissions and        #
+# limitations under the License.                                             #
+#--------------------------------------------------------------------------- #
+
+# snap_create host:parent_image snap_id vmid ds_id
+
+SRC=$1
+SNAP_ID=$2
+VM_ID=$3
+DS_ID=$4
+
+#--------------------------------------------------------------------------------
+
+if [ -z "${ONE_LOCATION}" ]; then
+    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
+    LIB_LOCATION=/usr/lib/one
+else
+    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
+    LIB_LOCATION=$ONE_LOCATION/lib
+fi
+
+DRIVER_PATH=$(dirname $0)
+
+source $TMCOMMON
+source ${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc
+
+#-------------------------------------------------------------------------------
+# Set dst path and dir
+#-------------------------------------------------------------------------------
+
+SRC_HOST=`arg_host $SRC`
+SRC_PATH=`arg_path $SRC`
+SRC_DIR=`dirname $SRC_PATH`
+DS_SYS_ID=$(echo $SRC_DIR | $AWK -F '/' '{print $(NF-1)}')
+
+#-------------------------------------------------------------------------------
+# Get Image information
+#-------------------------------------------------------------------------------
+
+DISK_ID=$(echo "$SRC_PATH" | $AWK -F. '{print $NF}')
+
+XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
+
+unset i j XPATH_ELEMENTS
+
+while IFS= read -r -d '' element; do
+    XPATH_ELEMENTS[i++]="$element"
+done < <(onevm show -x $VM_ID| $XPATH \
+                    /VM/DEPLOY_ID \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE )
+
+DEPLOY_ID="${XPATH_ELEMENTS[j++]}"
+SIZE="${XPATH_ELEMENTS[j++]}"
+CLONE="${XPATH_ELEMENTS[j++]}"
+
+#-------------------------------------------------------------------------------
+# Create snapshots (stored in the current volume)
+#-------------------------------------------------------------------------------
+
+POOL_NAME="lv-one-$VM_ID-pool"
+LV_NAME="lv-one-$VM_ID-$DISK_ID"
+VG_NAME="vg-one-$DS_SYS_ID"
+SNAP_NAME="${LV_NAME}_s$SNAP_ID"
+
+SNAP_CREATE_CMD=$(cat <<EOF
+    set -e -o pipefail
+
+    if timeout ${VIRSH_TIMEOUT:-60} virsh -c $LIBVIRT_URI domfsfreeze $DEPLOY_ID ; then
+        trap "virsh -c $LIBVIRT_URI domfsthaw $DEPLOY_ID || true" EXIT
+        ${SYNC}
+        ${SUDO} ${LVSCAN}
+        $SUDO $LVEXTEND -L +${SIZE}M $VG_NAME/$POOL_NAME
+        $SUDO $LVCREATE -s -n $SNAP_NAME $VG_NAME/$LV_NAME
+        ${SYNC}
+    else
+        echo "Unable to freeze VM; aborting"
+        exit 1
+    fi
+EOF
+)
+
+ssh_exec_and_log "$SRC_HOST" "$SNAP_CREATE_CMD" \
+                 "Error creating snapshot $SNAP_NAME"
+
+exit 0
