b #5699: Skip deactivation on FT states fs_lvm_ssh
(cherry picked from commit 7fdb46a650555bc58e57f30803d5d95d09c148b4)
(cherry picked from commit ce95cdf655c159ee60412f47852b23207f5c4ea4)

diff --git a/src/tm_mad/fs_lvm_ssh/mv b/src/tm_mad/fs_lvm_ssh/mv
--- a/src/tm_mad/fs_lvm_ssh/mv
+++ b/src/tm_mad/fs_lvm_ssh/mv
@@ -79,9 +79,10 @@ if [ "$(is_disk "$SRC_PATH")" -eq 1 ]; then
     DST_DEV="/dev/${DST_VG_NAME}/${LV_NAME}"
 
     # skip deactivate for `onevm resume` (after stop or undeploy)
-    # 9(49) = PROLOG_RESUME(+FAILURE)
+    # 9(49)  = PROLOG_RESUME(+FAILURE)
     # 31(50) = PROLOG_UNDEPLOY(+FAILURE)
-    if ! [[ "$LCM_STATE" =~ ^(9|31|49|50)$ ]]; then
+    # 60(61) = PROLOG_MIGRATE_UNKNOWN(+FAILURE)
+    if ! [[ "$LCM_STATE" =~ ^(9|31|49|50|60|61)$ ]]; then
         # deactivate
         CMD=$(cat <<EOF
             set -ex -o pipefail
