Performance improvements for ssh TM_MAD driver
Accessing and transferring local files via ssh connection causes
significant unnecessary system load (CPU utilization). This patch
takes into consideration data locality and reduces system load by
up to 50 % when transferring large files between the local machine
and a remote machine.

Patch outline
=============
The local machine is identified by comparing the host part of source
and destination string with the local hostname. In case no match
is detected, old driver behavior is used. If a match is detected
(in source or destination string), the `$HOST:` prefix is removed
and `$PATH` is considered to be locally available. Where ssh-to-ssh
pipeline is used, one part of this pipeline will be executed locally
(not as a remote command through an ssh connection).

Modified files
==============
 src/tm_mad/ssh/clone
 src/tm_mad/ssh/cpds
 src/tm_mad/ssh/mv
 src/tm_mad/ssh/mvds

diff --git a/src/tm_mad/ssh/clone b/src/tm_mad/ssh/clone
--- a/src/tm_mad/ssh/clone
+++ b/src/tm_mad/ssh/clone
@@ -44,11 +44,18 @@ DRIVER_PATH=$(dirname $0)
 # Set dst path and dir
 #-------------------------------------------------------------------------------
 
+WHOAMI=`hostname -f`
+if [ "$?" != "0" ]; then
+    log "Couldn't get local hostname!?"
+    unset WHOAMI
+fi
+
 SRC_PATH=`arg_path $SRC`
 DST_PATH=`arg_path $DST`
 SRC_PATH_SNAP="${SRC_PATH}.snap"
 DST_PATH_SNAP="${DST_PATH}.snap"
 
+SRC_HOST=`arg_host $SRC`
 DST_HOST=`arg_host $DST`
 
 DST_DIR=`dirname $DST_PATH`
@@ -85,7 +92,21 @@ http://*)
     ;;
 
 *)
-    log "Cloning $SRC in $DST_PATH"
+    if [ -n "$WHOAMI" ]; then
+        # check if SRC is the local machine
+        if [ "$WHOAMI" = "$SRC_HOST" ]; then
+            log "Replacing $SRC with $SRC_PATH"
+            SRC=$SRC_PATH
+        fi
+
+        # check if DST is the local machine
+        if [ "$WHOAMI" = "$DST_HOST" ]; then
+            log "Replacing $DST with $DST_PATH"
+            DST=$DST_PATH
+        fi
+    fi
+
+    log "Cloning $SRC into $DST"
     exec_and_log "$SCP -r $SRC $DST" "Error copying $SRC to $DST"
 
     if [ -d "${SRC_PATH_SNAP}" ]; then
diff --git a/src/tm_mad/ssh/mv b/src/tm_mad/ssh/mv
--- a/src/tm_mad/ssh/mv
+++ b/src/tm_mad/ssh/mv
@@ -41,6 +41,13 @@ fi
 # Return if moving a disk, we will move them when moving the whole system_ds
 # directory for the VM
 #-------------------------------------------------------------------------------
+
+WHOAMI=`hostname -f`
+if [ "$?" != "0" ]; then
+    log "Couldn't get local hostname!?"
+    unset WHOAMI
+fi
+
 SRC=`fix_dir_slashes $SRC`
 DST=`fix_dir_slashes $DST`
 
@@ -71,11 +78,27 @@ log "Moving $SRC to $DST"
 ssh_exec_and_log "$DST_HOST" "rm -rf '$DST_PATH'" \
     "Error removing target path to prevent overwrite errors"
 
-TAR_COPY="$SSH $SRC_HOST '$TAR -C $SRC_DS_DIR --sparse -cf - $SRC_VM_DIR'"
-TAR_COPY="$TAR_COPY | $SSH $DST_HOST '$TAR -C $DST_DIR --sparse -xf -'"
+# optimize transfer from local machine to remote machine
+if [ -n "$WHOAMI" ] && [ "$WHOAMI" = "$SRC_HOST" ]; then
+    log "$SRC is local, no need to use an ssh connection"
+    TAR_COPY="$TAR -C $SRC_DS_DIR --sparse -cf - $SRC_VM_DIR"
+else
+    log "$SRC is remote, using an ssh connection"
+    TAR_COPY="$SSH $SRC_HOST '$TAR -C $SRC_DS_DIR --sparse -cf - $SRC_VM_DIR'"
+fi
+
+# optimize transfer from remote machine to local machine
+if [ -n "$WHOAMI" ] && [ "$WHOAMI" = "$DST_HOST" ]; then
+    log "$DST is local, no need to use an ssh connection"
+    TAR_COPY="$TAR_COPY | $TAR -C $DST_DIR --sparse -xf -"
+else
+    log "$DST is remote, using an ssh connection"
+    TAR_COPY="$TAR_COPY | $SSH $DST_HOST '$TAR -C $DST_DIR --sparse -xf -'"
+fi
 
 exec_and_log "eval $TAR_COPY" "Error copying disk directory to target host"
 
-exec_and_log "$SSH $SRC_HOST rm -rf $SRC_PATH"
+ssh_exec_and_log "$SRC_HOST" "rm -rf '$SRC_PATH'" \
+    "Error removing source path after transfer"
 
 exit 0
diff --git a/src/tm_mad/ssh/mvds b/src/tm_mad/ssh/mvds
--- a/src/tm_mad/ssh/mvds
+++ b/src/tm_mad/ssh/mvds
@@ -45,6 +45,36 @@ SRC_PATH_SNAP="${SRC_PATH}.snap"
 DST_SNAP="${DST}.snap"
 
 #-------------------------------------------------------------------------------
+# Set variables
+#-------------------------------------------------------------------------------
+
+WHOAMI=`hostname -f`
+if [ "$?" != "0" ]; then
+    log "Couldn't get local hostname!?"
+    unset WHOAMI
+fi
+
+SRC_PATH=`arg_path $SRC`
+DST_PATH=`arg_path $DST`
+
+SRC_HOST=`arg_host $SRC`
+DST_HOST=`arg_host $DST`
+
+if [ -n "$WHOAMI" ]; then
+    # check if SRC is the local machine
+    if [ "$WHOAMI" = "$SRC_HOST" ]; then
+        log "Replacing $SRC with $SRC_PATH"
+        SRC=$SRC_PATH
+    fi
+
+    # check if DST is the local machine
+    if [ "$WHOAMI" = "$DST_HOST" ]; then
+        log "Replacing $DST with $DST_PATH"
+        DST=$DST_PATH
+    fi
+fi
+
+#-------------------------------------------------------------------------------
 # Move the image back to the datastore
 #-------------------------------------------------------------------------------
 
