feautre #3362: Delay clone operations for snapshots, this also to perform live snapshots

diff --git a/src/tm_mad/ceph/snap_delete b/src/tm_mad/ceph/snap_delete
--- a/src/tm_mad/ceph/snap_delete
+++ b/src/tm_mad/ceph/snap_delete
@@ -79,9 +79,6 @@ if [ -n "$CEPH_USER" ]; then
 fi
 
 SNAP_DELETE_CMD=$(cat <<EOF
-    RBD="${RBD}"
-    RBD_SRC="${RBD_SRC}"
-
     RBD_FORMAT=\$($RBD info $RBD_SRC | sed -n 's/.*format: // p')
 
     if [ "\${RBD_FORMAT}" != "2" ]; then
@@ -89,9 +86,37 @@ SNAP_DELETE_CMD=$(cat <<EOF
         exit 1
     fi
 
-    rbd_rm_r $RBD_DST-$SNAP_ID
+    \$($RBD --format json snap ls $RBD_DST | grep -Pq "(?<=\"name\":\")$SNAP_ID")
+
+    if [ \$? -eq 0 ]; then
+        RBD_TGT=$RBD_DST
+    else
+        POOL_NAME=\$(echo $RBD_DST | cut -f1 -d'/')
+        VOL_NAME=\$(echo $RBD_DST | cut -f2 -d'/')
+
+        RBD_TGT=\$($RBD ls \${POOL_NAME} | grep "\${VOL_NAME}-[^-]*$SNAP_ID[^-]*")
+        RBD_TGT="\${POOL_NAME}/\${RBD_TGT}"
+    fi
+
+    if [ -z "\${RBD_TGT}" ]; then
+        echo "Could not find a volume with snapshot $SNAP_ID" >&2
+        exit 1
+    fi
+
+    $RBD snap unprotect \${RBD_TGT}@$SNAP_ID
+    $RBD snap rm \${RBD_TGT}@$SNAP_ID
+
+    SNAPIDS=\$($RBD --format json snap ls \${RBD_TGT} | \
+               grep -Po '(?<="name":")\d+' | \
+               paste -d: -s)
+
+    if [ -z "\${SNAPIDS}" ]; then
+        $RBD rm \${RBD_TGT}
+    else
+        $RBD rename \${RBD_TGT} ${RBD_DST}-\${SNAPIDS}
+    fi
 EOF
 )
 
-ssh_exec_and_log_stdin "$SRC_HOST" "$SNAP_DELETE_CMD" "$CEPH_UTILS" \
+ssh_exec_and_log "$SRC_HOST" "$SNAP_DELETE_CMD" \
                  "Error deleting snapshot $RBD_DST-$SNAP_ID@$SNAP_ID"
diff --git a/src/tm_mad/ceph/snap_revert b/src/tm_mad/ceph/snap_revert
--- a/src/tm_mad/ceph/snap_revert
+++ b/src/tm_mad/ceph/snap_revert
@@ -34,8 +34,6 @@ DRIVER_PATH=$(dirname $0)
 source $TMCOMMON
 source ${DRIVER_PATH}/../../datastore/ceph/ceph.conf
 
-CEPH_UTILS=${DRIVER_PATH}/../../datastore/ceph/ceph_utils.sh
-
 #-------------------------------------------------------------------------------
 # Set dst path and dir
 #-------------------------------------------------------------------------------
@@ -79,9 +77,6 @@ if [ -n "$CEPH_USER" ]; then
 fi
 
 SNAP_REVERT_CMD=$(cat <<EOF
-    RBD="${RBD}"
-    RBD_SRC="${RBD_SRC}"
-
     RBD_FORMAT=\$($RBD info $RBD_SRC | sed -n 's/.*format: // p')
 
     if [ "\${RBD_FORMAT}" != "2" ]; then
@@ -89,11 +84,29 @@ SNAP_REVERT_CMD=$(cat <<EOF
         exit 1
     fi
 
-    rbd_rm_r $RBD_DST
+    SNAPIDS=\$($RBD --format json snap ls $RBD_DST | \
+               grep -Po '(?<="name":")\d+' | \
+               paste -d: -s)
 
-    $RBD clone $RBD_DST-$SNAP_ID@$SNAP_ID $RBD_DST
+    if [ -z "\${SNAPIDS}" ]; then
+        $RBD rm $RBD_DST
+    else
+        $RBD rename $RBD_DST $RBD_DST-\${SNAPIDS}
+    fi
+
+    POOL_NAME=\$(echo $RBD_DST | cut -f1 -d'/')
+    VOL_NAME=\$(echo $RBD_DST | cut -f2 -d'/')
+
+    RBD_TGT=\$($RBD ls \${POOL_NAME} | grep "\${VOL_NAME}-[^-]*$SNAP_ID[^-]*")
+
+    if [ -z "\$RBD_TGT" ]; then
+        echo "Could not find a volume with snapshot $SNAP_ID" >&2
+        exit 1
+    fi
+
+    $RBD clone \${POOL_NAME}/\${RBD_TGT}@$SNAP_ID $RBD_DST
 EOF
 )
 
-ssh_exec_and_log_stdin "$SRC_HOST" "$SNAP_REVERT_CMD" "$CEPH_UTILS" \
+ssh_exec_and_log "$SRC_HOST" "$SNAP_REVERT_CMD" \
                  "Error reverting snapshot $RBD_DST-$SNAP_ID@$SNAP_ID"
