F #7311: LXC Disk Snapshot support
It supports live snapshot operations for LXC and the following storage
drivers:

- fs_lvm
- ceph
- shared (only raw disks)
- local (only raw disks)

diff --git a/src/tm_mad/ceph/snap_create_live b/src/tm_mad/ceph/snap_create_live
--- a/src/tm_mad/ceph/snap_create_live
+++ b/src/tm_mad/ceph/snap_create_live
@@ -62,6 +62,7 @@ while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onevm show -x $VM_ID| $XPATH \
                     /VM/DEPLOY_ID \
+                    /VM/HISTORY_RECORDS/HISTORY[last\(\)]/VM_MAD \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CEPH_USER \
@@ -70,6 +71,7 @@ done < <(onevm show -x $VM_ID| $XPATH \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/TYPE )
 
 DEPLOY_ID="${XPATH_ELEMENTS[j++]}"
+VMM_MAD="${XPATH_ELEMENTS[j++]}"
 RBD_SRC="${XPATH_ELEMENTS[j++]}"
 CLONE="${XPATH_ELEMENTS[j++]}"
 CEPH_USER="${XPATH_ELEMENTS[j++]}"
@@ -104,12 +106,29 @@ if [ "${TYPE}" != 'RBD' ]; then
     exit 1
 fi
 
-SNAP_CREATE_CMD=$(cat <<EOF
-    set -e -o pipefail
-
+if [[ $VMM_MAD == 'lxc' ]]; then
+    FREEZE_CMD=$(cat <<EOT
+    if sudo lxc-freeze -n $DEPLOY_ID ; then
+        trap "sudo lxc-unfreeze -n $DEPLOY_ID" EXIT
+    else
+        echo "Could not freeze container $DEPLOY_ID" >&2
+        exit 1
+    fi
+EOT
+)
+else
+    FREEZE_CMD=$(cat <<EOT
     if timeout ${VIRSH_TIMEOUT:-60} virsh -c $LIBVIRT_URI domfsfreeze $DEPLOY_ID ; then
         trap "virsh -c $LIBVIRT_URI domfsthaw $DEPLOY_ID || true" EXIT
     fi
+EOT
+)
+fi
+
+SNAP_CREATE_CMD=$(cat <<EOF
+    set -e -o pipefail
+
+    $FREEZE_CMD
 
     RBD="${RBD}"
 
diff --git a/src/tm_mad/fs_lvm_ssh/snap_create_live b/src/tm_mad/fs_lvm_ssh/snap_create_live
--- a/src/tm_mad/fs_lvm_ssh/snap_create_live
+++ b/src/tm_mad/fs_lvm_ssh/snap_create_live
@@ -61,10 +61,12 @@ while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onevm show -x $VM_ID| $XPATH \
                     /VM/DEPLOY_ID \
+                    /VM/HISTORY_RECORDS/HISTORY[last\(\)]/VM_MAD \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE )
 
 DEPLOY_ID="${XPATH_ELEMENTS[j++]}"
+VMM_MAD="${XPATH_ELEMENTS[j++]}"
 SIZE="${XPATH_ELEMENTS[j++]}"
 CLONE="${XPATH_ELEMENTS[j++]}"
 
@@ -77,11 +79,7 @@ LV_NAME="lv-one-$VM_ID-$DISK_ID"
 VG_NAME="vg-one-$DS_SYS_ID"
 SNAP_NAME="${LV_NAME}_s$SNAP_ID"
 
-SNAP_CREATE_CMD=$(cat <<EOF
-    set -e -o pipefail
-
-    if timeout ${VIRSH_TIMEOUT:-60} virsh -c $LIBVIRT_URI domfsfreeze $DEPLOY_ID ; then
-        trap "virsh -c $LIBVIRT_URI domfsthaw $DEPLOY_ID || true" EXIT
+LVM_SNAP_CMD=$(cat <<EOF
         ${SYNC}
         ${SUDO} ${LVSCAN}
 
@@ -99,12 +97,36 @@ SNAP_CREATE_CMD=$(cat <<EOF
         fi
 
         ${SYNC}
+EOF
+)
+
+if [[ $VMM_MAD == 'lxc' ]]; then
+    SNAP_CREATE_CMD=$(cat <<EOT
+    set -e -o pipefail
+
+    if sudo lxc-freeze -n $DEPLOY_ID ; then
+        trap "sudo lxc-unfreeze -n $DEPLOY_ID" EXIT
+        $LVM_SNAP_CMD
+    else
+        echo "Could not freeze container $DEPLOY_ID" >&2
+        exit 1
+    fi
+EOT
+)
+else
+    SNAP_CREATE_CMD=$(cat <<EOF
+    set -e -o pipefail
+
+    if timeout ${VIRSH_TIMEOUT:-60} virsh -c $LIBVIRT_URI domfsfreeze $DEPLOY_ID ; then
+        trap "virsh -c $LIBVIRT_URI domfsthaw $DEPLOY_ID || true" EXIT
+        $LVM_SNAP_CMD
     else
         echo "Unable to freeze VM; aborting"
         exit 1
     fi
 EOF
 )
+fi
 
 ssh_exec_and_log "$SRC_HOST" "$SNAP_CREATE_CMD" \
                  "Error creating snapshot $SNAP_NAME"
diff --git a/src/tm_mad/qcow2/snap_create_live b/src/tm_mad/qcow2/snap_create_live
--- a/src/tm_mad/qcow2/snap_create_live
+++ b/src/tm_mad/qcow2/snap_create_live
@@ -54,6 +54,7 @@ done < <(onevm show -x $VMID| $XPATH \
                     /VM/TEMPLATE/DISK\[DISK_ID=$DISK_ID\]/TARGET \
                     /VM/TEMPLATE/DISK\[DISK_ID=$DISK_ID\]/FORMAT \
                     /VM/DEPLOY_ID \
+                    /VM/HISTORY_RECORDS/HISTORY[last\(\)]/VM_MAD \
                     '%m%/VM/TEMPLATE/DISK/TARGET')
 
 DISK_SRC="${XPATH_ELEMENTS[j++]}"
@@ -61,6 +62,7 @@ CLONE="${XPATH_ELEMENTS[j++]}"
 TARGET="${XPATH_ELEMENTS[j++]}"
 FORMAT="${XPATH_ELEMENTS[j++]}"
 DEPLOY_ID="${XPATH_ELEMENTS[j++]}"
+VMM_MAD="${XPATH_ELEMENTS[j++]}"
 ALL_DISKS="${XPATH_ELEMENTS[j++]}"
 
 SYSTEM_DS_PATH=$(dirname ${SRC_PATH})
@@ -78,6 +80,10 @@ SNAP_DIR="${DISK_PATH}.snap"
 SNAP_DIR_SHORT="${DISK_PATH_SHORT}.snap"
 
 if [ "$FORMAT" = "qcow2" ]; then
+    if [[ $VMM_MAD == 'lxc' ]]; then
+        echo "LXC driver does not support live qcow2 snapshots" >&2
+        exit 1
+    fi
     NEXT_SNAP_ID=$((SNAP_ID+1))
     SNAP_PATH="${SNAP_DIR}/${NEXT_SNAP_ID}"
     SNAP_PATH_SHORT="${SNAP_DIR_SHORT}/${NEXT_SNAP_ID}"
@@ -153,10 +159,18 @@ else
     CREATE_CMD="cp \"$DISK_PATH\" \"$SNAP_PATH\""
 fi
 
-CMD=$(cat <<EOT
-    set -ex -o pipefail
-    mkdir -p "$SNAP_DIR"
-
+if [[ $VMM_MAD == 'lxc' ]]; then
+    FREEZE_CMD=$(cat <<EOT
+    if sudo lxc-freeze -n $DEPLOY_ID ; then
+        trap "sudo lxc-unfreeze -n $DEPLOY_ID" EXIT
+    else
+        echo "Could not freeze container $DEPLOY_ID" >&2
+        exit 1
+    fi
+EOT
+)
+else
+    FREEZE_CMD=$(cat <<EOT
     if timeout ${VIRSH_TIMEOUT:-60} virsh -c $LIBVIRT_URI domfsfreeze $DEPLOY_ID ; then
         trap "virsh -c $LIBVIRT_URI domfsthaw $DEPLOY_ID" EXIT
     elif virsh -c $LIBVIRT_URI suspend $DEPLOY_ID; then
@@ -165,7 +179,15 @@ CMD=$(cat <<EOT
         echo "Could not domfsfreeze or suspend domain" >&2
         exit 1
     fi
+EOT
+)
+fi
 
+CMD=$(cat <<EOT
+    set -ex -o pipefail
+    mkdir -p "$SNAP_DIR"
+
+    $FREEZE_CMD
     $CREATE_CMD
 EOT
 )
diff --git a/src/tm_mad/ssh/snap_create_live b/src/tm_mad/ssh/snap_create_live
--- a/src/tm_mad/ssh/snap_create_live
+++ b/src/tm_mad/ssh/snap_create_live
@@ -54,9 +54,11 @@ while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onevm show -x $VMID| $XPATH \
                     /VM/DEPLOY_ID \
+                    /VM/HISTORY_RECORDS/HISTORY[last\(\)]/VM_MAD \
                     /VM/HISTORY_RECORDS/HISTORY[last\(\)]/DS_ID)
 
 DEPLOY_ID="${XPATH_ELEMENTS[j++]}"
+VMM_MAD="${XPATH_ELEMENTS[j++]}"
 DS_ID="${XPATH_ELEMENTS[j++]}"
 
 VM_DIR="$(dirname ${SRC_PATH})"
@@ -65,6 +67,26 @@ SNAP_DIR="${SRC_PATH}.snap"
 SNAP_PATH="${SNAP_DIR}/${SNAP_ID}"
 
 REPLICA_HOST=$(get_replica_host $DS_ID)
+
+if [[ $VMM_MAD == 'lxc' ]]; then
+    HYPERVISOR_CMD=$(cat <<EOT
+    if sudo lxc-freeze -n $DEPLOY_ID ; then
+        trap "sudo lxc-unfreeze -n $DEPLOY_ID" EXIT
+    else
+        echo "Could not freeze container $DEPLOY_ID" >&2
+        exit 1
+    fi
+
+    cp \${REAL_DISK} $SNAP_PATH
+EOT
+)
+else
+    HYPERVISOR_CMD=$(cat <<EOT
+    retry_if_no_error "active block job" 3 5  virsh -q -c ${LIBVIRT_URI} blockcopy ${DEPLOY_ID} \
+    --path \${REAL_DISK} --dest $SNAP_PATH --wait --finish
+EOT
+)
+fi
 
 CMD=$(cat <<EOT
 set -ex -o pipefail
@@ -79,8 +101,7 @@ else
     REAL_DISK="${SRC_PATH}"
 fi
 
-retry_if_no_error "active block job" 3 5  virsh -q -c ${LIBVIRT_URI} blockcopy ${DEPLOY_ID} \
-    --path \${REAL_DISK} --dest $SNAP_PATH --wait --finish
+$HYPERVISOR_CMD
 
 if [ -n "$REPLICA_HOST" ]; then
     ssh $REPLICA_HOST "mkdir -p $REPLICA_RECOVERY_SNAPS_DIR/$VMID"
