feature #3362: Return error if RBD target not found

diff --git a/src/datastore_mad/remotes/ceph/snap_flatten b/src/datastore_mad/remotes/ceph/snap_flatten
--- a/src/datastore_mad/remotes/ceph/snap_flatten
+++ b/src/datastore_mad/remotes/ceph/snap_flatten
@@ -79,6 +79,11 @@ SNAP_FLATTEN_CMD=$(cat <<EOF
 
     RBD_TGT=\$(rbd_find_snap $RBD_SRC $SNAP_ID)
 
+    if [ -z "\$RBD_TGT" ]; then
+        echo "Target RBD not found." >&2
+        exit 1
+    fi
+
     $RBD clone \${RBD_TGT}@$SNAP_ID $RBD_SRC.flatten
 
     $RBD flatten $RBD_SRC.flatten
diff --git a/src/tm_mad/ceph/cpds b/src/tm_mad/ceph/cpds
--- a/src/tm_mad/ceph/cpds
+++ b/src/tm_mad/ceph/cpds
@@ -96,6 +96,12 @@ COPY_CMD=$(cat <<EOF
         rbd_check_2 $RBD_DST
 
         RBD_DST=\$(rbd_find_snap $RBD_DST $SNAP_ID)
+
+        if [ -z "\$RBD_DST" ]; then
+            echo "Target RBD not found." >&2
+            exit 1
+        fi
+
         RBD_DST=\$RBD_DST@$SNAP_ID
     fi
 
diff --git a/src/tm_mad/ceph/snap_delete b/src/tm_mad/ceph/snap_delete
--- a/src/tm_mad/ceph/snap_delete
+++ b/src/tm_mad/ceph/snap_delete
@@ -92,6 +92,11 @@ SNAP_DELETE_CMD=$(cat <<EOF
 
     RBD_TGT=\$(rbd_find_snap $RBD_DST $SNAP_ID)
 
+    if [ -z "\$RBD_TGT" ]; then
+        echo "Target RBD not found." >&2
+        exit 1
+    fi
+
     $RBD snap unprotect \${RBD_TGT}@$SNAP_ID
     $RBD snap rm \${RBD_TGT}@$SNAP_ID
 
diff --git a/src/tm_mad/ceph/snap_revert b/src/tm_mad/ceph/snap_revert
--- a/src/tm_mad/ceph/snap_revert
+++ b/src/tm_mad/ceph/snap_revert
@@ -111,6 +111,11 @@ SNAP_REVERT_CMD=$(cat <<EOF
 
     RBD_TGT=\$(rbd_find_snap $RBD_DST $SNAP_ID)
 
+    if [ -z "\$RBD_TGT" ]; then
+        echo "Target RBD not found." >&2
+        exit 1
+    fi
+
     $RBD clone \${RBD_TGT}@$SNAP_ID $RBD_DST
 EOF
 )
