feature #1112: Use tar for tm_ssh/mv copies. Use iscsi helper functions

diff --git a/src/tm_mad/iscsi/mv b/src/tm_mad/iscsi/mv
--- a/src/tm_mad/iscsi/mv
+++ b/src/tm_mad/iscsi/mv
@@ -24,6 +24,7 @@
 SRC=$1
 DST=$2
 
+
 if [ -z "${ONE_LOCATION}" ]; then
     TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
 else
@@ -31,6 +32,10 @@ else
 fi
 
 . $TMCOMMON
+
+DRIVER_PATH=$(dirname $0)
+
+source ${DRIVER_PATH}/../../datastore/iscsi/iscsi.conf
 
 # {:path=>
 #   "/var/lib/one/remotes/tm/iscsi/mv o202:/var/lib/one//datastores/0/3/disk.0 rama:/var/lib/one/datastores/0/3/disk.0",
@@ -47,11 +52,22 @@ fi
 # directory for the VM
 #-------------------------------------------------------------------------------
 SRC_PATH=`arg_path $SRC`
+DST_PATH=`arg_path $DST`
+
 SRC_HOST=`arg_host $SRC`
+DST_HOST=`arg_host $DST`
+
+DST_DIR=`dirname $DST_PATH`
 
 if [ `is_disk $SRC_PATH` -eq 0 ]; then
-    log "Removing directory"
-    ssh_exec_and_log "$SRC_HOST" "rm -rf $SRC_PATH"
+    ssh_make_path $DST_HOST $DST_DIR
+
+    log "Moving $SRC to $DST"
+
+    exec_and_log "$SCP -r $SRC $DST" "Could not copy $SRC to $DST"
+
+    ssh_exec_and_log "$SRC_HOST" "rm -rf $SRC_PATH" \
+        "Could not remove $SRC_HOST:$SRC_PATH"
 
 	exit 0
 fi
@@ -61,14 +77,50 @@ if [ "$SRC" == "$DST" ]; then
 	exit 0
 fi
 
-log "Logging out $IQN"
+if is_iscsi "$SRC_HOST"; then
+   log "Logging out of $IQN in $SRC_HOST"
 
-LOGOUT_CMD=$(cat <<EOF
-    set -e
-    $SUDO $(iscsiadm_logout "$IQN")
+    LOGOUT_CMD=$(cat <<EOF
+        set -e
+        IQN=\$(readlink $SRC_PATH |grep -o 'iqn.*$')
+        IQN=\${IQN%-lun-1}
+        $SUDO $(iscsiadm_logout "\$IQN")
 EOF
 )
-ssh_exec_and_log "$SRC_HOST" "$LOGOUT_CMD" \
-    "Error logging out $IQN"
+    ssh_exec_and_log "$SRC_HOST" "$LOGOUT_CMD" \
+        "Error logging out $SRC_HOST:$SRC_PATH (IQN)"
+fi
+
+if is_iscsi "$DST_HOST"; then
+    log "Logging in to IQN in $SRC_HOST"
+
+    log "Getting IQN from $SRC_HOST:$SRC_PATH"
+
+    IQN=$($SSH "$SRC_HOST" "readlink $SRC_PATH |grep -o 'iqn.*$'" )
+    IQN=${IQN%-lun-1}
+
+    if [ -z "$IQN" ]; then
+        log_error "Error getting IQN"
+        exit 1
+    fi
+
+    TARGET_HOST=$(iqn_get_host "$IQN")
+
+    LOGIN_CMD=$(cat <<EOF
+        set -e
+        mkdir -p $DST_DIR
+        $SUDO $(iscsiadm_discovery "$TARGET_HOST")
+        $SUDO $(iscsiadm_discovery "$TARGET_HOST")
+        $SUDO $(iscsiadm_login "$IQN" "$TARGET_HOST")
+        sleep 1
+        DISK_BY_PATH=\$(ls /dev/disk/by-path/*$IQN-lun-1)
+        ln -s "\$DISK_BY_PATH" "$DST_PATH"
+EOF
+)
+
+    ssh_exec_and_log "$DST_HOST" "$LOGIN_CMD" \
+        "Error logging in $IQN"
+fi
+
 
 exit 0
