M #-: Backport security issues (#2342)

diff --git a/src/datastore_mad/remotes/fs/cp b/src/datastore_mad/remotes/fs/cp
--- a/src/datastore_mad/remotes/fs/cp
+++ b/src/datastore_mad/remotes/fs/cp
@@ -152,12 +152,27 @@ if [ -n "$BRIDGE_LIST" ]; then
         ssh_exec_and_log "$DST_HOST" "$CONVERT_CMD" \
                          "Error converting $DST in $DST_HOST"
     fi
+
+    FORMAT=$(ssh_monitor_and_log $DST_HOST "set -e -o pipefail; $QEMU_IMG info $DST | grep \"^file format:\" | awk '{print \$3}'")
+
+    # if ssh_monitor_and_log fails RC is returned
+    if [[ $FORMAT =~ '^[0-9]+$' ]]; then
+        exit -1
+    fi
 else
     mkdir -p "$BASE_PATH"
     multiline_exec_and_log "set -e -o pipefail; $COPY_COMMAND" "Error copying $SRC to $DST"
 
     if [ "x$CONVERT" = 'xyes' ] && [ -n "$DRIVER" ]; then
         multiline_exec_and_log "$CONVERT_CMD" "Error converting $DST"
+    fi
+
+    FORMAT=$($QEMU_IMG info $DST | grep "^file format:" | awk '{print $3}' || :)
+
+    if [ -z $FORMAT ]; then
+        rm -rf $DST
+        log_error "Unknown image format src=$SRC"
+        exit -1
     fi
 fi
 
