F #2755: Add Guacamole Apache for remote access (#92)

diff --git a/src/sunstone/bin/sunstone-server b/src/sunstone/bin/sunstone-server
--- a/src/sunstone/bin/sunstone-server
+++ b/src/sunstone/bin/sunstone-server
@@ -25,6 +25,7 @@ if [ -z "$ONE_LOCATION" ]; then
     SUNSTONE_LOG_ERROR=/var/log/one/sunstone.error
     SUNSTONE_CONF=/etc/one/sunstone-server.conf
     NOVNC_SERVER=/usr/bin/novnc-server
+    GUACAMOLE_SERVER=/usr/bin/guac-server
 else
     SUNSTONE_PID=$ONE_LOCATION/var/sunstone.pid
     SUNSTONE_SERVER=$ONE_LOCATION/lib/sunstone/sunstone-server.rb
@@ -33,6 +34,7 @@ else
     SUNSTONE_LOG_ERROR=$ONE_LOCATION/var/sunstone.error
     SUNSTONE_CONF=$ONE_LOCATION/etc/sunstone-server.conf
     NOVNC_SERVER=$ONE_LOCATION/bin/novnc-server
+    GUACAMOLE_SERVER=$ONE_LOCATION/bin/guac-server
 fi
 
 setup()
@@ -59,12 +61,15 @@ setup()
   fi
 }
 
-
 start()
 {
-  if [ "$1" = "-n" ]; then
-    novnc=1
-  fi
+  while getopts "ng" opt; do
+    case "${opt}" in
+      n) novnc=1 ;;
+      g) guacamole=1 ;;
+      *) echo "Invalid option: $OPTARG" 1>&2 ;;
+    esac
+  done
 
   if [ ! -f "$SUNSTONE_SERVER" ]; then
     echo "Cannot find $SUNSTONE_SERVER."
@@ -80,6 +85,15 @@ start()
     fi
   fi
 
+  if [ "$guacamole" = "1" ]; then
+    # Start guacamole server
+    $GUACAMOLE_SERVER start
+
+    if [ "$?" != "0" ]; then
+      echo "Could not start Guacamole server" 1>&2
+    fi
+  fi
+
   # Start the sunstone daemon
   touch $SUNSTONE_LOCK_FILE
 
@@ -87,6 +101,7 @@ start()
     echo "Error creating lock file" 1>&2
 
     $NOVNC_SERVER stop
+    $GUACAMOLE_SERVER stop
     exit 1
   fi
 
@@ -97,6 +112,7 @@ start()
     echo "Error executing sunstone-server."
     echo "Check $SUNSTONE_LOG_ERROR and $SUNSTONE_LOG for more information"
     [ "$novnc" = "1" ] && $NOVNC_SERVER stop
+    [ "$guacamole" = "1" ] && $GUACAMOLE_SERVER stop
     exit 1
   else
     echo $LASTPID > $SUNSTONE_PID
@@ -109,6 +125,7 @@ start()
     echo "Error executing sunstone-server."
     echo "Check $SUNSTONE_LOG_ERROR and $SUNSTONE_LOG for more information"
     [ "$novnc" = "1" ] && $NOVNC_SERVER stop
+    [ "$guacamole" = "1" ] && $GUACAMOLE_SERVER stop
     exit 1
   fi
 
@@ -120,12 +137,19 @@ start()
 #
 stop()
 {
-  if [ "$1" = "-n" ]; then
-    novnc=1
-  fi
+  while getopts "ng" opt; do
+    case "${opt}" in
+      n) novnc=1 ;;
+      g) guacamole=1 ;;
+      *) echo "Invalid option: $OPTARG" 1>&2 ;;
+    esac
+  done
 
   # Stop novnc server
   [ "$novnc" = "1" ] && $NOVNC_SERVER stop
+
+  # Stop guacamole server
+  [ "$guacamole" = "1" ] && $GUACAMOLE_SERVER stop
 
   if [ ! -f $SUNSTONE_PID ]; then
     echo "Couldn't find sunstone-server process pid." >&2
@@ -146,16 +170,16 @@ stop()
 case "$1" in
   start)
     setup
-    start -n
+    start -ng
     ;;
   stop)
-    stop -n
+    stop -ng
     exit $?
     ;;
   restart)
-    stop -n 2> /dev/null
+    stop -ng 2> /dev/null
     setup
-    start -n
+    start -ng
     ;;
   start-sunstone)
     setup
@@ -165,7 +189,7 @@ case "$1" in
     stop
     ;;
   restart-sunstone)
-    stop -n 2> /dev/null
+    stop -ng 2> /dev/null
     setup
     start
     ;;
