F #2410: VM Autorefresh (#180)
Signed-off-by: Frederick Borges <fborges@opennebula.io>

diff --git a/src/sunstone/bin/sunstone-server b/src/sunstone/bin/sunstone-server
--- a/src/sunstone/bin/sunstone-server
+++ b/src/sunstone/bin/sunstone-server
@@ -26,6 +26,7 @@ if [ -z "$ONE_LOCATION" ]; then
     SUNSTONE_CONF=/etc/one/sunstone-server.conf
     NOVNC_SERVER=/usr/bin/novnc-server
     GUACAMOLE_SERVER=/usr/bin/guac-server
+    AUTOREFRESH_SERVER=/usr/bin/autorefresh-server
 else
     SUNSTONE_PID=$ONE_LOCATION/var/sunstone.pid
     SUNSTONE_SERVER=$ONE_LOCATION/lib/sunstone/sunstone-server.rb
@@ -35,6 +36,7 @@ else
     SUNSTONE_CONF=$ONE_LOCATION/etc/sunstone-server.conf
     NOVNC_SERVER=$ONE_LOCATION/bin/novnc-server
     GUACAMOLE_SERVER=$ONE_LOCATION/bin/guac-server
+    AUTOREFRESH_SERVER=$ONE_LOCATION/bin/autorefresh-server
 fi
 
 setup()
@@ -63,10 +65,11 @@ setup()
 
 start()
 {
-  while getopts "ng" opt; do
+  while getopts "ngr" opt; do
     case "${opt}" in
       n) novnc=1 ;;
       g) guacamole=1 ;;
+      r) autorefresh=1 ;;
       *) echo "Invalid option: $OPTARG" 1>&2 ;;
     esac
   done
@@ -94,6 +97,15 @@ start()
     fi
   fi
 
+  if [ "$autorefresh" = "1" ]; then
+    # Start Autorefresh server
+    $AUTOREFRESH_SERVER start
+
+    if [ "$?" != "0" ]; then
+      echo "Could not start Autorefresh server" 1>&2
+    fi
+  fi
+
   # Start the sunstone daemon
   touch $SUNSTONE_LOCK_FILE
 
@@ -102,6 +114,7 @@ start()
 
     $NOVNC_SERVER stop
     $GUACAMOLE_SERVER stop
+    $AUTOREFRESH_SERVER stop
     exit 1
   fi
 
@@ -113,6 +126,7 @@ start()
     echo "Check $SUNSTONE_LOG_ERROR and $SUNSTONE_LOG for more information"
     [ "$novnc" = "1" ] && $NOVNC_SERVER stop
     [ "$guacamole" = "1" ] && $GUACAMOLE_SERVER stop
+    [ "$autorefresh" = "1" ] && $AUTOREFRESH_SERVER stop
     exit 1
   else
     echo $LASTPID > $SUNSTONE_PID
@@ -126,6 +140,7 @@ start()
     echo "Check $SUNSTONE_LOG_ERROR and $SUNSTONE_LOG for more information"
     [ "$novnc" = "1" ] && $NOVNC_SERVER stop
     [ "$guacamole" = "1" ] && $GUACAMOLE_SERVER stop
+    [ "$autorefresh" = "1" ] && $AUTOREFRESH_SERVER stop
     exit 1
   fi
 
@@ -137,10 +152,11 @@ start()
 #
 stop()
 {
-  while getopts "ng" opt; do
+  while getopts "ngr" opt; do
     case "${opt}" in
       n) novnc=1 ;;
       g) guacamole=1 ;;
+      r) autorefresh=1 ;;
       *) echo "Invalid option: $OPTARG" 1>&2 ;;
     esac
   done
@@ -150,6 +166,9 @@ stop()
 
   # Stop guacamole server
   [ "$guacamole" = "1" ] && $GUACAMOLE_SERVER stop
+
+  # Stop autorefresh server
+  [ "$autorefresh" = "1" ] && $AUTOREFRESH_SERVER stop
 
   if [ ! -f $SUNSTONE_PID ]; then
     echo "Couldn't find sunstone-server process pid." >&2
@@ -170,16 +189,16 @@ stop()
 case "$1" in
   start)
     setup
-    start -ng
+    start -ngr
     ;;
   stop)
-    stop -ng
+    stop -ngr
     exit $?
     ;;
   restart)
-    stop -ng 2> /dev/null
+    stop -ngr 2> /dev/null
     setup
-    start -ng
+    start -ngr
     ;;
   start-sunstone)
     setup
@@ -189,7 +208,7 @@ case "$1" in
     stop
     ;;
   restart-sunstone)
-    stop -ng 2> /dev/null
+    stop -ngr 2> /dev/null
     setup
     start
     ;;
