M #-:vCenter monitor service start

diff --git a/src/im_mad/im_exec/one_im_sh b/src/im_mad/im_exec/one_im_sh
--- a/src/im_mad/im_exec/one_im_sh
+++ b/src/im_mad/im_exec/one_im_sh
@@ -18,15 +18,48 @@
 
 if [ -z "${ONE_LOCATION}" ]; then
     MAD_LOCATION=/usr/lib/one/mads
+    VAR_LOCATION=/var/lib/one
 else
     MAD_LOCATION=$ONE_LOCATION/lib/mads
+    VAR_LOCATION=$ONE_LOCATION/var
 fi
 
 export DRIVER_NAME="one_im_sh_${BASH_ARGV##* }"
 
-# Explicitly execute the vCenter monitor driver in the background
-# This way we don't have to wait until OpenNebula
-# issues the add_hosts commands to know about missing hosts
-#(/usr/bin/env ruby $VAR_LOCATION/remotes/im/lib/vcenter_monitor.rb &)
+#-------------------------------------------------------------------------------
+#  vCenter Monitor Service startup routine
+#-------------------------------------------------------------------------------
+# Explicitly execute the vCenter monitor driver initialization and run it in the
+# background. This way we don't have to wait until OpenNebula issues the
+# add_hosts commands to know about missing hosts
+#-------------------------------------------------------------------------------
+if [ "${BASH_ARGV##* }" = "vcenter" ]; then
+
+    FIFO_PATH="/tmp/vcenter_monitor.fifo"
+    VMON_PATH="$VAR_LOCATION/remotes/im/lib/vcenter_monitor.rb"
+
+    # Sanitize previous instances
+    VMON_PIDS=$(ps axuww | grep "ruby $VMON_PATH" | grep -v grep | awk '{print $2}')
+
+    if [ -n "$VMON_PIDS" ]; then
+        kill $VMON_PIDS
+    fi
+
+    # Create server FIFO
+    rm -f $FIFO_PATH > /dev/null 2>&1
+    mkfifo $FIFO_PATH
+
+    # Start & check vcenter monitor service
+    /usr/bin/env ruby $VMON_PATH </dev/null &>/dev/null &
+
+    sleep 3
+
+    VMON_PIDS=$(ps axuww | grep "ruby $VMON_PATH" | grep -v grep | awk '{print $2}')
+
+    if [ -z "$VMON_PIDS" ]; then
+        echo "Cannot start vcenter_monitor service"
+        exit 1
+    fi
+fi
 
 exec $MAD_LOCATION/one_im_exec -l $*
