Backport of bug #1174

diff --git a/src/image_mad/remotes/fs/fsrc b/src/image_mad/remotes/fs/fsrc
--- a/src/image_mad/remotes/fs/fsrc
+++ b/src/image_mad/remotes/fs/fsrc
@@ -60,7 +60,15 @@ $CANONICAL_STR
 EOF
 )
 
-echo "$IMAGE_REPOSITORY_PATH/`echo $CANONICAL_MD5 | cut -d ' ' -f1`"
+IMAGE_HASH=$(echo $CANONICAL_MD5 | cut -d ' ' -f1)	
+IMAGE_HASH=$(basename "$IMAGE_HASH")
+	
+if [ -z "$IMAGE_HASH" ]; then	
+	log_error "Error generating the path in generate_image_path."
+	exit 1
+fi	
+	
+echo "${IMAGE_REPOSITORY_PATH}/${IMAGE_HASH}"
 }
 
 function fs_du {
