Bug #678: Startup should create dir for pid file if it does not exists
(cherry picked from commit e0c813b59138aea45d44739d00abda7a9dc83abe)

diff --git a/share/scripts/one b/share/scripts/one
--- a/share/scripts/one
+++ b/share/scripts/one
@@ -52,6 +52,15 @@ BACKUP="true"
 #------------------------------------------------------------------------------
 setup()
 {
+    ONE_PID_DIR=`dirname $ONE_PID`
+
+    mkdir -p $ONE_PID_DIR
+
+    if [ ! -w $ONE_PID_DIR ]; then
+        echo "$ONE_PID_DIR is not writable, cannot start oned or scheduler."
+        exit 1
+    fi
+
     if [ -f $LOCK_FILE ]; then
         if [ -f  $ONE_PID ]; then
             ONEPID=`cat $ONE_PID`
