Getting correctly the oned return codes.
git-svn-id: http://svn.opennebula.org/trunk@76 3034c82b-c49b-4eb3-8279-a7acafdc01c0

diff --git a/share/scripts/one b/share/scripts/one
--- a/share/scripts/one
+++ b/share/scripts/one
@@ -1,4 +1,4 @@
-#! /bin/sh 
+#! /bin/sh
 
 if [ -z "$ONE_LOCATION" ]; then 
 	echo "ONE_LOCATION is not defined"
@@ -56,7 +56,7 @@ start()
 	fi
 		
 	# Start the one daemon
-	$ONED -f 2>&1 &
+	$ONED -f 2>&1 & 
 	
 	LASTRC=$?
 	LASTPID=$!
@@ -66,6 +66,14 @@ start()
 		exit 1			
 	else
 		echo $LASTPID > $ONE_PID
+	fi
+	
+	sleep 1
+	ps $LASTPID &> /dev/null
+	
+	if [ $? -ne 0 ]; then
+		echo "Error executing $ONED."
+		exit 1
 	fi
 	
 	# Start the scheduler
