Fix 'one start' with existent DB but nonexistent auth file
The start script assumes that an existing database implies
credentials located in either one of these places:
  * $HOME/.one/one_auth or
  * $ONE_AUTH

Now, if the database was setup once correctly but the
credentials file does not exist or ONE_AUTH is not set
anymore, oned runs into a segmentation fault.

The change prevents this situation by always checking for
user credentials file wheter the DB exists or not.

diff --git a/share/scripts/one b/share/scripts/one
--- a/share/scripts/one
+++ b/share/scripts/one
@@ -136,14 +136,12 @@ start()
         exit 1
     fi
 
-    if [ ! -f "$ONE_DB" ]; then
-        if [ ! -f "$HOME/.one/one_auth" ]; then
-            if [ -z "$ONE_AUTH" ]; then
-                echo "You should have ONE_AUTH set the first time you start"
-                echo "OpenNebula as it is used to set the credentials for"
-                echo "the administrator user."
-                exit 1
-            fi
+    if [ -z "$HOME" ] || [ ! -f "$HOME/.one/one_auth" ]; then
+        if [ -z "$ONE_AUTH" ] || [ ! -f "$ONE_AUTH" ]; then
+            echo "Could not find one_auth credentials file: Please create a one_auth"
+            echo "file in either \$ONE_AUTH or \$HOME/.one/one_auth containing the"
+            echo "OpenNebula administrator users credentials."
+            exit 1
         fi
     fi
 
