one command changes and hem retries

diff --git a/share/scripts/one b/share/scripts/one
--- a/share/scripts/one
+++ b/share/scripts/one
@@ -19,27 +19,33 @@
 if [ -z "$ONE_LOCATION" ]; then
     ONE_PID=/var/run/one/oned.pid
     ONE_SCHEDPID=/var/run/one/sched.pid
+    ONE_HEMPID=/var/run/one/hem.pid
     ONE_CONF=/etc/one/oned.conf
     ONE_DB=/var/lib/one/one.db
     ONE_LOG=/var/log/one/oned.log
     ONE_SCHED_LOG=/var/log/one/sched.log
+    ONE_HEM_LOG=/var/log/one/onehem.log
     ONE_XMLRPC_LOG=/var/log/one/one_xmlrpc.log
 
     ONED=/usr/bin/oned
     ONE_SCHEDULER=/usr/bin/mm_sched
+    ONE_HEM=/usr/bin/onehem-server
 
     LOCK_FILE=/var/lock/one/one
 else
     ONE_PID=$ONE_LOCATION/var/oned.pid
     ONE_SCHEDPID=$ONE_LOCATION/var/sched.pid
+    ONE_HEMPID=$ONE_LOCATION/var/hem.pid
     ONE_CONF=$ONE_LOCATION/etc/oned.conf
     ONE_DB=$ONE_LOCATION/var/one.db
     ONE_LOG=$ONE_LOCATION/var/oned.log
     ONE_SCHED_LOG=$ONE_LOCATION/var/sched.log
+    ONE_HEM_LOG=$ONE_LOCATION/var/onehem.log
     ONE_XMLRPC_LOG=$ONE_LOCATION/var/one_xmlrpc.log
 
     ONED=$ONE_LOCATION/bin/oned
     ONE_SCHEDULER=$ONE_LOCATION/bin/mm_sched
+    ONE_HEM=$ONE_LOCATION/bin/onehem-server
 
     LOCK_FILE=$ONE_LOCATION/var/.lock
 fi
@@ -74,7 +80,15 @@ setup()
             ONESCHEDPID=`cat $ONE_SCHEDPID`
             ps $ONESCHEDPID > /dev/null 2>&1
             if [ $? -eq 0 ]; then
-                echo "The scheduler is still running (PID:$ONEPID). Please try 'one stop' first."
+                echo "The scheduler is still running (PID:$ONESCHEDPID). Please try 'one stop' first."
+                exit 1
+            fi
+        fi
+        if [ -f  $ONE_HEMPID ]; then
+            ONEHEMPID=`cat $ONE_HEMPID`
+            ps $ONEHEMPID > /dev/null 2>&1
+            if [ $? -eq 0 ]; then
+                echo "The hem is still running (PID:$ONEHEMPID). Please try 'one stop' first."
                 exit 1
             fi
         fi
@@ -91,6 +105,8 @@ stop()
     stop_oned
 
     stop_sched
+
+    stop_hem
 }
 
 stop_oned()
@@ -121,6 +137,14 @@ stop_sched()
     fi
 }
 
+stop_hem()
+{
+    if [ -f $ONE_HEMPID ]; then
+        kill `cat $ONE_HEMPID` > /dev/null 2>&1
+        rm -f $ONE_HEMPID > /dev/null 2>&1
+    fi
+}
+
 #------------------------------------------------------------------------------
 # Function that starts the daemons
 #------------------------------------------------------------------------------
@@ -133,6 +157,11 @@ start()
 
     if [ ! -x "$ONE_SCHEDULER" ]; then
         echo "Can not find $ONE_SCHEDULER."
+        exit 1
+    fi
+
+    if [ ! -x "$ONE_HEM" ]; then
+        echo "Can not find $ONE_HEM."
         exit 1
     fi
 
@@ -152,6 +181,9 @@ start()
 
     # Start the scheduler
     start_sched
+
+    # Start hook execution manager server
+    start_hem
 
     # Wait for the daemons to warm up
     sleep 3
@@ -215,6 +247,24 @@ start_sched()
     fi
 }
 
+start_hem()
+{
+    if [ "$BACKUP" = "true" ];then
+        [ -f "$ONE_HEM_LOG" ] && mv $ONE_HEM_LOG{,.$(date '+%Y%m%d%H%M%S')}
+    fi
+    $ONE_HEM&
+
+    LASTRC=$?
+    LASTPID=$!
+
+    if [ $LASTRC -ne 0 ]; then
+        echo "Error executing $ONE_HEM"
+        exit 1
+    else
+        echo $LASTPID > $ONE_HEMPID
+    fi
+}
+
 #------------------------------------------------------------------------------
 #------------------------------------------------------------------------------
 
@@ -230,13 +280,13 @@ case "$1" in
         ;;
     stop)
         stop
-        echo "oned and scheduler stopped"
+        echo "oned, scheduler and hem stopped"
         ;;
     restart)
         stop
         setup
         start
-        echo "oned and scheduler restarted"
+        echo "oned, scheduler and hem restarted"
         ;;
     start-sched)
         start_sched
@@ -249,8 +299,19 @@ case "$1" in
         sleep 1
         start_sched
         ;;
+    start-hem)
+        start_hem
+        ;;
+    stop-hem)
+        stop_hem
+        ;;
+    restart-hem)
+        stop_hem
+        sleep 1
+        start_hem
+        ;;
     *)
-        echo "Usage: one [-f] {start|stop|restart|start-sched|stop-sched|restart-sched}" >&2
+        echo "Usage: one [-f] {start|stop|restart|start-sched|stop-sched|restart-sched|start-hem|stop-hem|restart-hem}" >&2
         echo "Options:" >&2
         echo "  -f  Do not backup log files." >&2
         exit 3
