F #1550: New Scheduler Framework for OpenNebula & DRS scheduler
This commits introduces a new framework for OpenNebula, it is based on
standard the OpenNebula middleware access driver (mad) model. Benefits
compared to the current implementation:

* Less overhead on API server and streamlined communications
* Ease integration with third party schedulers
* New "optimize" action to balance the workload of a cluster
* Embedded Plan Manager to apply optimization and deployment plans with
  custom parameters for the scheduling window
* Custom optimization policies per cluster

This commits introduces 2 schedulers:

* Rank scheduler based on the match-making algorithm present in 6.x
  series
* OpenNebula DRS an optimization algorithm based on an ILP solver for
  placement and cluster optimization

Also new API calls has been added for onecluster as well as the CLI
updates to expose them.

co-authored-by: MarioRobres <mrobres@opennebula.io>
co-authored-by: Pavel Czerny <pczerny@opennebula.io>
co-authored-by: Mirko Stojiljkovic <mstojiljkovic@opennebula.io>
co-authored-by: Valentyn Bohdan <vbohdan@opennebula.io>

diff --git a/share/scripts/one b/share/scripts/one
--- a/share/scripts/one
+++ b/share/scripts/one
@@ -18,7 +18,6 @@
 
 if [ -z "$ONE_LOCATION" ]; then
     ONE_PID=/var/run/one/oned.pid
-    ONE_SCHEDPID=/var/run/one/sched.pid
     ONE_CONF=/etc/one/oned.conf
     ONE_DB=/var/lib/one/one.db
     ONE_LOG=/var/log/one/oned.log
@@ -28,13 +27,11 @@ if [ -z "$ONE_LOCATION" ]; then
     ONE_MONITOR_LOG=/var/log/one/monitor.log
 
     ONED=/usr/bin/oned
-    ONE_SCHEDULER=/usr/bin/mm_sched
     ONE_HEM=/usr/bin/onehem-server
 
     LOCK_FILE=/var/lock/one/one
 else
     ONE_PID=$ONE_LOCATION/var/oned.pid
-    ONE_SCHEDPID=$ONE_LOCATION/var/sched.pid
     ONE_CONF=$ONE_LOCATION/etc/oned.conf
     ONE_DB=$ONE_LOCATION/var/one.db
     ONE_LOG=$ONE_LOCATION/var/oned.log
@@ -44,7 +41,6 @@ else
     ONE_MONITOR_LOG=$ONE_LOCATION/var/monitor.log
 
     ONED=$ONE_LOCATION/bin/oned
-    ONE_SCHEDULER=$ONE_LOCATION/bin/mm_sched
     ONE_HEM=$ONE_LOCATION/bin/onehem-server
 
     LOCK_FILE=$ONE_LOCATION/var/lock/.lock
@@ -63,7 +59,7 @@ setup()
     mkdir -p $ONE_PID_DIR
 
     if [ ! -w $ONE_PID_DIR ]; then
-        echo "$ONE_PID_DIR is not writable, cannot start oned or scheduler."
+        echo "$ONE_PID_DIR is not writable, cannot start oned."
         exit 1
     fi
 
@@ -73,14 +69,6 @@ setup()
             ps $ONEPID > /dev/null 2>&1
             if [ $? -eq 0 ]; then
                 echo "ONE is still running (PID:$ONEPID). Please try 'one stop' first."
-                exit 1
-            fi
-        fi
-        if [ -f  $ONE_SCHEDPID ]; then
-            ONESCHEDPID=`cat $ONE_SCHEDPID`
-            ps $ONESCHEDPID > /dev/null 2>&1
-            if [ $? -eq 0 ]; then
-                echo "The scheduler is still running (PID:$ONESCHEDPID). Please try 'one stop' first."
                 exit 1
             fi
         fi
@@ -96,8 +84,6 @@ setup()
 stop()
 {
     stop_oned
-
-    stop_sched
 
     stop_hem
 }
@@ -122,14 +108,6 @@ stop_oned()
     fi
 }
 
-stop_sched()
-{
-    if [ -f $ONE_SCHEDPID ]; then
-        kill `cat $ONE_SCHEDPID` > /dev/null 2>&1
-        rm -f $ONE_SCHEDPID > /dev/null 2>&1
-    fi
-}
-
 stop_hem()
 {
     onehem-server stop > /dev/null 2>&1
@@ -142,11 +120,6 @@ start()
 {
     if [ ! -x "$ONED" ]; then
         echo "Can not find $ONED."
-        exit 1
-    fi
-
-    if [ ! -x "$ONE_SCHEDULER" ]; then
-        echo "Can not find $ONE_SCHEDULER."
         exit 1
     fi
 
@@ -169,9 +142,6 @@ start()
     # Start the one daemon
     start_oned
 
-    # Start the scheduler
-    start_sched
-
     # Start hook execution manager server
     start_hem
 
@@ -184,13 +154,6 @@ start()
 
     if [ $? -ne 0 ]; then
         echo "oned failed to start"
-        STARTED="false"
-    fi
-
-    ps `cat $ONE_SCHEDPID` > /dev/null 2>&1
-
-    if [ $? -ne 0 ]; then
-        echo "scheduler failed to start"
         STARTED="false"
     fi
 
@@ -217,24 +180,6 @@ start_oned()
         exit 1
     else
         echo $LASTPID > $ONE_PID
-    fi
-}
-
-start_sched()
-{
-    if [ "$BACKUP" = "true" ];then
-        [ -f "$ONE_SCHED_LOG" ] && mv $ONE_SCHED_LOG{,.$(date '+%Y%m%d%H%M%S')}
-    fi
-    $ONE_SCHEDULER&
-
-    LASTRC=$?
-    LASTPID=$!
-
-    if [ $LASTRC -ne 0 ]; then
-        echo "Error executing $ONE_SCHEDULER"
-        exit 1
-    else
-        echo $LASTPID > $ONE_SCHEDPID
     fi
 }
 
@@ -280,19 +225,8 @@ case "$1" in
         setup
         start
         ;;
-    start-sched)
-        start_sched
-        ;;
-    stop-sched)
-        stop_sched
-        ;;
-    restart-sched)
-        stop_sched
-        sleep 1
-        start_sched
-        ;;
     *)
-        echo "Usage: one [-f] {start|stop|restart|start-sched|stop-sched|restart-sched}" >&2
+        echo "Usage: one [-f] {start|stop|restart}" >&2
         echo "Options:" >&2
         echo "  -f  Do not backup log files." >&2
         exit 3
