F #-: TM/LVM/clone: improve error reporting (#3771)
LVM drivers require that the frontend has filesystem access to base images. As it's a common point
of confusion during manual setup, check it specifically to ease troubleshooting.

Signed-off-by: Guillermo Ramos <gramos@opennebula.io>

diff --git a/src/tm_mad/fs_lvm/clone b/src/tm_mad/fs_lvm/clone
--- a/src/tm_mad/fs_lvm/clone
+++ b/src/tm_mad/fs_lvm/clone
@@ -79,10 +79,12 @@ SIZE="${XPATH_ELEMENTS[j++]}"
 ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"
 TM_MAD="${XPATH_ELEMENTS[j++]}"
 
-# Remove potential " and ' chars to avoid bash syntax errors on ssh command below.
-FILE_TYPE=`file --brief ${SRC_PATH} | tr -d \"\'`
-FILE_SIZE=`fs_size "${SRC_PATH}" YES`
+if [ ! -r "${SRC_PATH}" ]; then
+    log_error "Can't access image file '${SRC_PATH}' from frontend, please check datastore configuration"
+    exit 1
+fi
 
+FILE_SIZE=`fs_size "${SRC_PATH}" YES`
 if [ $? -ne 0 ]; then
     FILE_SIZE=0
 fi
@@ -91,6 +93,8 @@ if [ $FILE_SIZE -gt $SIZE ]; then
     SIZE="$FILE_SIZE"
 fi
 
+# Remove potential " and ' chars to avoid bash syntax errors on ssh command below.
+FILE_TYPE=`file --brief ${SRC_PATH} | tr -d \"\'`
 # Extend the SIZE so the encrypted file fits in the LV
 if [[ "$FILE_TYPE" =~ "LUKS encrypted file" ]]; then
     SIZE=$(( SIZE + 4 ))
diff --git a/src/tm_mad/fs_lvm_ssh/clone b/src/tm_mad/fs_lvm_ssh/clone
--- a/src/tm_mad/fs_lvm_ssh/clone
+++ b/src/tm_mad/fs_lvm_ssh/clone
@@ -84,9 +84,12 @@ ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"
 LVM_THIN_ENABLE="${XPATH_ELEMENTS[j++],,}"
 TM_MAD="${XPATH_ELEMENTS[j++]}"
 
-FILE_SIZE=`fs_size "${SRC_PATH}" YES`
-FILE_TYPE=`file --brief ${SRC_PATH}`
+if [ ! -r "${SRC_PATH}" ]; then
+    log_error "Can't access image file '${SRC_PATH}' from frontend, please check datastore configuration"
+    exit 1
+fi
 
+FILE_SIZE=`fs_size "${SRC_PATH}" YES`
 if [ $? -ne 0 ]; then
     FILE_SIZE=0
 fi
@@ -95,6 +98,7 @@ if [ $FILE_SIZE -gt $SIZE ]; then
     SIZE="$FILE_SIZE"
 fi
 
+FILE_TYPE=`file --brief ${SRC_PATH}`
 # Extend the SIZE so the encrypted file fits in the LV
 if [[ "$FILE_TYPE" =~ "LUKS encrypted file" ]]; then
     SIZE=$(( SIZE + 4 ))
